version: '3.9'

services:
  app:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: .
    container_name: app
    env_file: env/.app_env
    ports:
      - 8888:8888
#    restart: on-failure
    depends_on:
      db:
        condition: service_healthy
    links:
      - db:db

  db:
    image: postgres:13.1
    container_name: db
    env_file: env/.db_env
    ports:
      - 5432:5432
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/10-init.sql
      - postgres:/var/lib/postgresql/data
#    networks:
#      - db
    healthcheck:
      #test: ["CMD-SHELL", "pg_is_ready -U postgres"]
      test: /usr/bin/pg_isready
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

#networks:
#  db:
#    driver: bridge

volumes:
  postgres:
    #external: true

#  db:
#    build: ./postgres